name: CD_CI
env:
  EB_PACACHE_S3_BUCKET_NAME: "flask-app-pack"
  EB_APP_NAME: "myflask"
  EB_ENV_NAME: "myflask-env"
  DEPLOY_PACK_NAME: "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME: "eu-central-1a"
on:
  push:
    branches:
      - master

jobs:
  my_ci_part:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git clone our repo
      uses: actions/checkout@v1
    
    - name: Create zip
      uses: zip -r "flask_app_${{ github.sha }}.zip" ./ -x *.git*
      
      
