name: CD_CI
env:
  EB_PACACHE_S3_BUCKET_NAME: "flask-app-pack"
  EB_APP_NAME: "myflask"
  EB_ENV_NAME: "myflask-env"
  DEPLOY_PACK_NAME: "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME: "eu-central-1c"
on:
  push:
    branches:
      - master

jobs:
       
  my_ci_part:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git clone our repo
      uses: actions/checkout@v1
    
    - name: Create zip
      run: zip -r ${{ env.DEPLOY_PACK_NAME }} ./ -x *.git*
      
    - name: Configure my aws Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-secret-key-id    : ${{ secrets.MY_AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_KEY }}
        aws-region           : ${{ env.AWS_REGION_NAME }}
    
    - name: Copy deployment package to s3 backet
      run: aws s3 cp ${{ env.DEPLOY_PACK_NAME }} s3//${{ env.EB_PACACHE_S3_BUCKET_NAME }}/
    
    - name: Print happy massege
      run: echo "CI Pipeline part finished succefully"
     
